CREATE TABLE IF NOT EXISTS user_entity (
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS hit_entity (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES user_entity(id),
    x INTEGER NOT NULL,
    y FLOAT NOT NULL,
    r INTEGER NOT NULL,
    hit BOOLEAN NOT NULL,
    date DATE DEFAULT CURRENT_DATE
);
